env:
  num_players: 4
  deck_size: 60
  seed: 16112004
  random: False
  debug_print: False

sim:
  iter: 25

nn:
  input_layer: 661
  hidden_layer_shared: 1024
  hidden_layer_each: 512

train:
  iter: 1000
  game_iterations: 24
  gamma: 0.995
  lambda: 0.95
  epochs: 4
  minibatch_size: 256
  clip_eps: 0.2
  a1: 0.5
  a2: 0.02
  lr: 1.5e-4
